apiHost: 127.0.0.1
apiPort: 5000
siteAdmin:
    name: Alice
    email: alice@example.com
guestNotify:
    mode: 0
    smtpSender: '"Alice" <foo@example.com>'
    smtpHost: example.com
    smtpPort: 465
    smtpUsername: username
    smtpPassword: password
    smtpSecure: false
    title: "[YOUR_SITENAME] {{name}}, you got a new reply!"
reCAPTCHA:
    enabled: false
    secretKey: ''
    minimumScore: 0.1
antiSpamProvider: false
